---
title: "Tutorials"
---
```{r, child="_setup.Rmd"}
```

#Developing research questions

For this project, we will investigate how writing is structured in academic disciplines. To start thinking about these issues, I recommend investigating major readings on the topic.  Two texts to start with are Hyland's (2006) "Disciplinary differences: Language variation in academic discourses" and Biber's (1988) [*Variation across speech and writing*](https://wfu.summon.serialssolutions.com/#!/search?bookMark=ePnHCXMw42LgTQStzc4rAe_hSmEG7Q81NDQDdS3M2RjENUKznZNCAzSdg8DH6UNlTDhg4yIGZhYmJsZGnAzKYcDOIth1CongGkOhuCA1NTlDAdjDVigHnfiTl87DwJoGjKVUXgaWkqJSYHkq5eYa4uyhW55WGg8d_ogHtgcsLMxAlx_jlVTGlITN_wBVgSYITYwByLM-rQ)

#Data for text analysis

For the first stage of the project, we will be building a corpus of academic research in a field/discipline you are interested in. To do so, you should gather between 10-15 articles from the field that can provide a representative sample of research writing in the field. Before you begin collecting the articles, it may be useful to investigate writing in your chosen field and reflect on what your sample corpus should include.  Questions to consider can begin with: 
* What types of research writing occur in the field?  What types of articles are usually published in the field?  
* What journals are the most widely read in the field?  What general or specific topics are widely published in the field?  
* How quickly does the field change?  What time period should you look to when choosing your articles?  The last year?  The last decade?  

Finally, once you have considered these questions, we will talk as a class about building a larger database together that allows for analysis *across* disciplines and types of research writing.  What considerations need to be made to make sure your individual sample is representative of the field but can also be compared with a sub-corpus from another field?  

1. Gathering data
2. Cleaning and preparing data
3. Managing data and documentation

#Analyzing and interpreting data

1. Matching research questions with methods
2. Common methods in textual analysis
3. Reporting results
4. Visualizing results
5. Interpreting results

##Using R for text analysis

*This bit is empty and will remain so until I have a half-day of free time and a pot of coffee.*  

